name: AAAntiWorm
main: com.khjxiaogu.AAAntiWorm.AAAntiWorm
version: 0.1
author: khjxiaogu
softdepend: [PlaceholderAPI]
commands:
  points: 
    aliases: mps
    description: 点数插件命令
    permission: AAAntiWorm.default
    usage: /mps
permissions: 
  AAAntiWorm.default:
   description: 使用点数插件的权限
   default: true
  AAAntiWorm.modify:
   description: 修改点数插件的权限
   default: op
  AAAntiWorm.debug:
   description: 重载点数插件的权限
   default: op
  AAAntiWorm.pay:
   description: 支付所有点数的权限
   default: op
  AAAntiWorm.top:
   description: 查看点数排序的权限
   default: op
  AAAntiWorm.<点数ID>.pay:
   description: 支付特定点数的权限
   default: op
  AAAntiWorm.<点数ID>.modify:
   description: 修改特定点数的权限
   default: op
  AAAntiWorm.<点数ID>.top:
   description: 查看特定点数排序的权限
   default: op
